[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbwMQvKOA2djV4vbN2NuGtd4sakc0ZAMPlbmulZzRMlFQHkbtNMkRWigHcDYp_mK961l/exec"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200